### ISSUE TITLE
Graphic Composer doesn't support Line Graph(gfx 3.9.0).

### ISSUE THREAD

**Issue by kick2nick** [Microchip-MPLAB-Harmony/gfx#12]
After adding the "Line Graph" widget, the Legarto Graphic Composer closes up without error messages.

**Comment by MHGC** [comment]
That is not exactly a lot to go on to help identify the problem.  We are not seeing this problem with any existing project we have.

If you can upload a composer design that can consistently reproduce the problem, that will be really helpful.  If not, can you provide more details?  Linux/Mac/Windows?  Screen resolution?  How many layers are on the particular screen?  How many widgets are already there?  What kind of widgets?  How many screens?

Also, composer creates a log file in the folder where the executable is located (for windows it is at "gfx\middleware\legato\composer\windows").  Can you upload that file?

**Comment by kick2nick** [comment]
[MyProject.zip](https://github.com/Microchip-MPLAB-Harmony/gfx/files/5821412/MyProject.zip)
Windows, I attached composer design.
I haven't found log file in Harmony directory "gfx\middleware\legato\composer\windows".
I have the same problem with example apps.

**Comment by MHGC** [comment]
Ok, we see it now.  We will be able to fix this with gfx-3.9.1.  Thanks for reporting.
