### ISSUE TITLE
Graphic Composer Slider Issue(gfx 3.9.0)

### ISSUE THREAD

**Issue by kick2nick** [Microchip-MPLAB-Harmony/gfx#13]
![image](https://user-images.githubusercontent.com/58635163/104815533-32402c00-5826-11eb-8158-e3c633bfc36c.png)
![image](https://user-images.githubusercontent.com/58635163/104815536-35d3b300-5826-11eb-8eab-c3d2fe60fcba.png)
Hello!
Slider option "Orientation" in Legato Graphic Composer doesn't work.
After code generation I always have vertically oriented slider.
Target controller: atsamd51.
System: Windows.

**Comment by MHGC** [comment]
We see it on our end to.  We will look into it.  Thanks!
