### ISSUE TITLE
gfx 3.9.1 line graph

### ISSUE THREAD

**Issue by kick2nick** [Microchip-MPLAB-Harmony/gfx#15]
Hello, I have some problems with using line graph.

Project and environment:
Windows 10
Mplab x IDE 5.45
mhc 3.6.2
gfx 3.9.1
Board same54Xplained with ATSAME54P20A.
Display 320x240 parallel 8-bit 8080.

1. I have compilation errors in legato_widget_line_graph_skin_classic. I have changed the lines below to make the project compile.
![image](https://user-images.githubusercontent.com/58635163/106582286-e1824000-6554-11eb-93d9-f5962cfaf4f1.png)
![image](https://user-images.githubusercontent.com/58635163/106582311-e810b780-6554-11eb-8a08-03b73ad320ea.png)

2. "setDataInSeries" function doesn't work for me. I used it like in Aria showcase reloaded:
For example I have one seriesData(10 elements) and I want to change 5th element.
Screen0_LineGraphWidget0->fn->setDataInSeries(Screen0_LineGraphWidget0,0,5,100);
Other functions are working propery.  Maybe I'm missing something

Thanks!

**Comment by MHGC** [comment]
Hi,
Item 1 is noted.  We will fix it in the next release (gfx v3.9.2).
We are investigating on item 2 and will report back.
Thanks!

**Comment by MHGC** [comment]
Looks like there is an issue indeed.

Can you try replace the function with this code here?

`static leResult setDataInSeries(leLineGraphWidget* _this, 
                                int32_t seriesID,
                                int32_t index,
                                int32_t value)
{
    leLineGraphDataSeries* series;
    int32_t* data;
    (void)value; // unused
    
    LE_ASSERT_THIS();
    
    if(seriesID >= (int32_t) _this->dataSeries.size)
        return LE_FAILURE;
    
    series = leArray_Get(&_this->dataSeries, seriesID);
    if(index >= (int32_t) series->data.size)
        return LE_FAILURE;
    
    getValueDamagedRect(_this,
                        seriesID,
                        index,
                        &prevDamagedRect);
    series->data.values[index] = value;
    getValueDamagedRect(_this,
                        seriesID,
                        index,
                        &damagedRect);
    
    leRectCombine(&prevDamagedRect, &damagedRect, &damagedRect);
    _this->fn->_damageArea(_this, &damagedRect);
    
    return LE_SUCCESS;
}`

**Comment by kick2nick** [comment]
It works now, thanks!
