### ISSUE TITLE
Legato graphics composer don't open

### ISSUE THREAD

**Issue by raf6410** [Microchip-MPLAB-Harmony/gfx#16]
Hi,

I try to understand how work legato, spi and ili 9488.
I use project exemple "legato_qs_mzef_cu2_cpro_spi.X"
But it is impossible to open "LEGATO GRAPHICS COMPOSER"

I use a fresh install of windows 10 pro version 20h2 with MPLAB v5.45

could you help me.

RAF6410

**Comment by mhc-microchip** [comment]
If it's a fresh install, please try installing one of the Microsoft Visual Studio C/C++ runtime libraries.

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by raf6410** [comment]
tanks a lot, 
now it's ok
