### ISSUE TITLE
gfx rendering issues

### ISSUE THREAD

**Issue by simeonfelis** [Microchip-MPLAB-Harmony/gfx#24]
Using SAM54XPlained and a ST7789S display via 4-wire SPI
Compiler XC32 v1.40
GFX Library 3.10.0
Due to #22 I cannot upgrade GFX
There are actually two issues:
* black lines on re-rendering screens
![lines on re-rendering](https://github.com/simeonfelis/gfx/raw/master/IMG_0203_small.JPG)
* artifacts in/around circles
![artifacts in circle](https://github.com/simeonfelis/gfx/raw/master/IMG_0201_small.JPG)

Both issues happen wether alpha-blending is enabled or not in legato composer

A sample project can be found [here](https://github.com/simeonfelis/gfx/raw/master/mcu_eval.zip)

With the user-button on SAM54XPlained the screen toggles. After the first toggle one can see the first black in the tiny circle; after the second toggle another black line appears as depicted. After a reset when the first screen is shown no black line is shown.

The dots in and around the circle widget are always visible. It looks like a bug in the circle draw algorithm.

**Comment by simeonfelis** [comment]
I just saw the gfx 3.11.1 release and retried. The issue with the black lines on re-rendering are gone. Thanks!

The remaining issue with the dots in and around the circle widget are still present, though.

**Comment by microchip-gfx** [comment]
Best guess is that the circle artifacts are due to the use of low accuracy fixed point math when doing the trig calculations for the circles.  Recommend using pre-drawn images to avoid this.

**Comment by simeonfelis** [comment]
OK, I hoped I could save 200bytes flash. Every byte saved to helps avoid running into supply chain issues. Also saves kittens.
