### ISSUE TITLE
Legato Composer Not Show Widget Correctly

### ISSUE THREAD

**Issue by osugiw** [Microchip-MPLAB-Harmony/gfx#30]
Hi everyone, currently I'm making project using MPLAB IDE X 6.0. I encounter problem while using Legato graphics composer, which is my widget won't show image that I already imported as an asset. 
![image](https://user-images.githubusercontent.com/51029305/205214048-6f9c4bc4-315e-4634-a4b0-ea9b917d0ee0.png)

System Information: 
Edition: Windows 11 Home Single Language
Version: 22H2
OS Build: 22621.819
Processor: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Ram: 8.00 GB (7.77 GB usable)

**Comment by osugiw** [comment]
Finally found the bugs, the problem is because my harmony folder is located in folder with space contained ex: "self learning" then I changed to "self-learning" and the problem is solved

**Comment by MHGC** [comment]
Thank you for the feedback @osugiw .  

Are you saying the entire harmony project folder (the one containing all of core/csp/gfx etc.) has a name containing space?

How about your application?  Is it stored under the same folder structure?

**Comment by osugiw** [comment]
> Thank you for the feedback @osugiw .
> 
> Are you saying the entire harmony project folder (the one containing all of core/csp/gfx etc.) has a name containing space?
> 
> How about your application? Is it stored under the same folder structure?

Yes, my harmony project folder is located under a folder that name containing space and I tried to replace the space with '-'.
My application was also located in the same folder structure.

![image](https://user-images.githubusercontent.com/51029305/205328769-8bca3aac-d76e-4c6b-a64c-6c76d737461e.png)

**Comment by osugiw** [comment]
> Thank you for the feedback @osugiw .
> 
> Are you saying the entire harmony project folder (the one containing all of core/csp/gfx etc.) has a name containing space?
> 
> How about your application? Is it stored under the same folder structure?

I also have problem in legato graphic composer also while inserting Label Widget to my screen canvas, the text didn't appear. Do you know what caused the problem?

![image](https://user-images.githubusercontent.com/51029305/205329850-b3c70ba5-a0af-49fa-a9eb-de307eb794f1.png)

**Comment by MHGC** [comment]
From your screenshot, I see that the font does not have a font assigned to it.  That is why the string is not showing up.

Here is a wiki with a user guide for this topic.  There are additional user guides you may need later.
https://github.com/mchpgfx/legato.docs/wiki/How-to-Add-Text

**Comment by osugiw** [comment]
> From your screenshot, I see that the font does not have a font assigned to it. That is why the string is not showing up.
> 
> Here is a wiki with a user guide for this topic. There are additional user guides you may need later. https://github.com/mchpgfx/legato.docs/wiki/How-to-Add-Text

Yeah I think that's the problem, I will try again and get back again! Thanks for the reference!

**Comment by osugiw** [comment]
> From your screenshot, I see that the font does not have a font assigned to it. That is why the string is not showing up.
> 
> Here is a wiki with a user guide for this topic. There are additional user guides you may need later. https://github.com/mchpgfx/legato.docs/wiki/How-to-Add-Text

Thankyou sir now it displays it works! Then I'll close this issue.
